# Generated by Django 5.0.8 on 2024-08-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrationFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.TextField(max_length=100)),
                ('ownerName', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=200)),
                ('cuisineType', models.TextField(max_length=100)),
                ('businessLicenceNo', models.TextField(max_length=100)),
                ('panCardNumber', models.TextField(max_length=100)),
            ],
        ),
    ]
