# Generated by Django 5.0.8 on 2024-08-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_businesslicenceno_registrationfpage_businesslicence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationfpage',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationfpage',
            name='businessLicence',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationfpage',
            name='cuisine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationfpage',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationfpage',
            name='ownerName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationfpage',
            name='panCard',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationfpage',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationfpage',
            name='restaurantName',
            field=models.CharField(max_length=100),
        ),
    ]
