# Generated by Django 5.0.8 on 2024-08-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_registrationfpage_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationfpage',
            old_name='cuisine',
            new_name='cuisineType',
        ),
    ]
